### ISSUE TITLE
add the possibility to use iam role instead of explicit using aws access keys

### ISSUE THREAD

**Issue by mokevnin** [refile/refile-s3#1]

**Comment by artempartos** [comment]
:+1:  need this feature too

**Comment by jnicklas** [comment]
I don't know what is missing to make this work. Please expand upon this issue, or ideally send a PR.

**Comment by mokevnin** [comment]
Explanation http://docs.amazonaws.cn/en_us/AWSSdkDocsRuby/latest/DeveloperGuide/ruby-dg-roles.html.

**Comment by jnicklas** [comment]
@mokevnin so what exactly is missing to support this?

**Comment by mokevnin** [comment]
AWS access keys should be optional. aws-ruby-sdk try to use iam role by default.

**Comment by artempartos** [comment]
Update PR
