### ISSUE TITLE
Can't install with Refile 0.6.0

### ISSUE THREAD

**Issue by callmeed** [refile/refile-s3#11]
I noticed Refile was tagged with version 0.6.0 today. This gem has a dependency of '~> 0.50' and therefore won't install with it. Can we safely bump that dependency?

**Comment by monkbroc** [comment]
Or relax the dependency to `"refile", "~> 0.5"` like `refile-mini_magick`?

**Comment by jnicklas** [comment]
I was planning to release them simultanesously, but I ran into a problem, so it'll have to wait until tomorrow.

**Comment by monkbroc** [comment]
Good :crescent_moon: and see you tomorrow then :)

**Comment by jnicklas** [comment]
Good morning! New gem is released.

**Comment by paulanunda** [comment]
thanks @jnicklas!!!
