### ISSUE TITLE
Minimum Ruby version

### ISSUE THREAD

**Issue by monkbroc** [refile/refile-s3#12]
It's a small thing, but I think you should specify `spec.required_ruby_version = '>= 2.1.0'` in the gemspec because of `verify_uploadable def upload(uploadable)`. Methods return a symbol only on Ruby >= 2.1.

**Comment by jnicklas** [comment]
Fixed. Though it depends on `refile` which already has a Ruby version requirement, so it shouldn't be possible to install on older rubies anyway.
