### ISSUE TITLE
Retry download at least once

### ISSUE THREAD

**Issue by sobrinho** [refile/refile-s3#19]
Sometimes the S3 timeouts the connection and then refile raises an exception because of that:

```
Errno::ETIMEDOUT

Connection timed out - connect(2) for "my-bucket.s3.amazonaws.com" port 443
```

I've seen this error a couple times before and just retrying the connection it works.

What you think?

We could retry at least once to ensure that is not a temporary failure.

**Comment by hiromipaw** [comment]
HI @sobrinho,
Thanks for reaching out, which version of the aws gem are you using?

**Comment by sobrinho** [comment]
aws-sdk 2.1.35

I'm not seeing this error anymore, seems like the connectivity issues was resolved on Amazon.

If we start to see this again, I will reopen, thanks!
