### ISSUE TITLE
Not compatible with `aws-sdk v3`

### ISSUE THREAD

**Issue by swapnils19** [refile/refile-s3#34]
I just upgraded to `aws-sdk v3` and got a compatibility error.
As per the current master [gemspec](https://github.com/refile/refile-s3/blob/78a74b60a597dd1174b0599be919689d41d5f118/refile-s3.gemspec#L23), they have locked the `aws-sdk` to `version 2`.

**Comment by bobbytables** [comment]
This actually isn't even compatible with 2.x anymore. The aws-sdk has undergone a lot of updates.

**Comment by AknEp** [comment]
+1
I wanna use refile with latest S3 SDK ...

**Comment by sobrinho** [comment]
Fixed on master.
